[build-system]
requires = ["flit_core >=3.7"]
build-backend = "flit_core.buildapi"

[project]
name = "pyparse"
version = "0.1.0"
description = "A python code parser, compatible with the SAR Kieker Tool"
authors = [{name = "Daphné Larrivain", email = "daphne.larrivain@ecole.ensicaen.fr"}]