class State:
    UNKNOWN = "++unknown-component++"
    IMPORTED = "++imported++"
    METHOD = "++imported-method++"
    UNRESOLVED = "++unresolved++"
    KNOWN = "++known++"
    FOUND = "++found++"
    CLASS = "++class++"
    ITERVAR = "++iter-var++"
    PARAM = "++param++"
    
    NONE = "++none++"
    LAMBDA = "++lambda++"
    EMPTY_COLLECTION = "++empty-collection++"
    EMPTY = ""